# Generated by Django 3.2.25 on 2024-12-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240713_1117'),
        ('blog', '0006_alter_comment_author'),
    ]

    operations = [
    ]
